-- 为塔罗师表添加更多联系方式字段
ALTER TABLE readers 
ADD COLUMN wechat VARCHAR(100) DEFAULT NULL COMMENT '微信号',
ADD COLUMN qq VARCHAR(50) DEFAULT NULL COMMENT 'QQ号',
ADD COLUMN xiaohongshu VARCHAR(100) DEFAULT NULL COMMENT '小红书账号',
ADD COLUMN douyin VARCHAR(100) DEFAULT NULL COMMENT '抖音账号',
ADD COLUMN other_contact TEXT DEFAULT NULL COMMENT '其他联系方式';

-- 更新现有的contact_info字段注释
ALTER TABLE readers MODIFY COLUMN contact_info TEXT COMMENT '联系信息描述';
ALTER TABLE readers MODIFY COLUMN phone VARCHAR(20) COMMENT '电话号码';

-- 查看更新后的表结构
DESCRIBE readers;
